server:
  port: 8083
  servlet:
    context-path: /notification
spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

notification:
  email:
    brevo-url: https://api.brevo.com
    # Use an environment variable for secrets; keep the current value as a default fallback.
    brevo-apikey: ${NOTIFICATION_BREVO_APIKEY:yd6h31ZkASjQgUHq}
