server:
  port: 8888
app:
  api-prefix: /api/v1

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=2
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2

#jwt:
#  secretKey: ${JWT_SECRET_KEY:VpKMvbaC6AdlBFwJv+1uw8Fxmk1X4NbHx4LZifIS82A=}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
