server:
  port: 8082
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  expiryHour: 1
  expiryDay: 14
  secretKey: ${JWT_SECRET_KEY}